"""empty message

Revision ID: 950449085bfe
Revises: 
Create Date: 2023-10-21 19:29:19.704643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950449085bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=20), nullable=False, comment='员工姓名'),
    sa.Column('employee_department', sa.String(length=20), nullable=False, comment='员工所属部门名'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_employee_employee_id'), ['employee_id'], unique=True)

    op.create_table('t_invite',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('visitor_name', sa.String(length=20), nullable=False),
    sa.Column('visitor_mobile', sa.String(length=11), nullable=False),
    sa.Column('visitor_num', sa.SmallInteger(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('visitor_car_number', sa.String(length=10), nullable=True),
    sa.Column('visitor_reason', sa.String(length=50), nullable=True),
    sa.Column('visitor_unit', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['t_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_invite')
    with op.batch_alter_table('t_employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_employee_employee_id'))

    op.drop_table('t_employee')
    # ### end Alembic commands ###
